"""Account authentication. Hosted PostgreSQL for Cloud; explicit SQLite for local use."""
from contextlib import contextmanager, suppress
from functools import lru_cache
from hashlib import sha256
from pathlib import Path
import secrets
import sqlite3
import time
from urllib.parse import parse_qs, urlsplit

from argon2 import PasswordHasher
from argon2.exceptions import InvalidHashError, VerificationError
from email_validator import EmailNotValidError, validate_email
import psycopg

# OWASP Argon2id minimum: 19 MiB, two iterations, one lane. Unique random salts
# are generated by argon2-cffi, never supplied or reused by the application.
_HASHER = PasswordHasher(memory_cost=19456, time_cost=2, parallelism=1)
MIN_PASSWORD_LENGTH = 15
MAX_PASSWORD_LENGTH = 128
ATTEMPT_WINDOW = 300
MAX_ATTEMPTS = 5
REMEMBER_SECONDS = 30 * 24 * 60 * 60
_UNAVAILABLE = 'Account storage is temporarily unavailable. Please try again later.'
_BAD_CREDENTIALS = 'Incorrect email or password.'


class AuthError(Exception):
    """Safe message that may be shown to the user."""


def normalize_email(email):
    if not isinstance(email, str) or len(email) > 320:
        raise AuthError('Enter a valid email address.')
    try:
        result = validate_email(email.strip(), check_deliverability=False)
    except EmailNotValidError:
        raise AuthError('Enter a valid email address.') from None
    # ActionPilot treats account emails case-insensitively, including local parts.
    return result.normalized.casefold()


def _validate_password(password):
    if not isinstance(password, str) or not MIN_PASSWORD_LENGTH <= len(password) <= MAX_PASSWORD_LENGTH:
        raise AuthError(f'Use a password with {MIN_PASSWORD_LENGTH}–{MAX_PASSWORD_LENGTH} characters.')


@lru_cache(maxsize=1)
def _dummy_hash():
    # Unknown emails perform the same password verification work as real users.
    return _HASHER.hash(secrets.token_urlsafe(32))


class AccountStore:
    """Short-lived connections; no passwords, connections or users cached in UI."""

    def __init__(self, *, database_url=None, sqlite_path=None):
        if not database_url and not sqlite_path:
            raise AuthError('Account storage is not configured. Add AUTH_DATABASE_URL in Streamlit secrets.')
        self.database_url = database_url
        self.sqlite_path = Path(sqlite_path) if sqlite_path else None
        self.sslmode = 'require'
        if database_url:
            if not isinstance(database_url, str):
                raise AuthError('Invalid account database configuration.')
            try:
                url = urlsplit(database_url)
                mode = parse_qs(url.query).get('sslmode', ['require'])
                if url.scheme not in ('postgresql', 'postgres') or not url.hostname:
                    raise ValueError
            except ValueError:
                raise AuthError('Invalid account database configuration.') from None
            if len(mode) != 1 or mode[0] not in ('require', 'verify-ca', 'verify-full'):
                raise AuthError('Account database connections must use TLS.')
            self.sslmode = mode[0]

    def _execute(self, conn, sql, values=()):
        return conn.execute(sql.replace('?', '%s') if self.database_url else sql, values)

    @contextmanager
    def _connection(self):
        conn = None
        try:
            if self.database_url:
                conn = psycopg.connect(self.database_url, sslmode=self.sslmode,
                                       connect_timeout=10, options='-c statement_timeout=10000')
                # Serialize bootstrap DDL, including concurrent first signups.
                conn.execute('SELECT pg_advisory_xact_lock(81472931)')
            else:
                self.sqlite_path.parent.mkdir(parents=True, exist_ok=True)
                conn = sqlite3.connect(self.sqlite_path, timeout=10)
                self.sqlite_path.chmod(0o600)
                conn.execute('BEGIN IMMEDIATE')
            conn.execute('''CREATE TABLE IF NOT EXISTS auth_users (
                email TEXT PRIMARY KEY, password_hash TEXT NOT NULL,
                created_at BIGINT NOT NULL)''')
            conn.execute('''CREATE TABLE IF NOT EXISTS auth_attempts (
                identity TEXT PRIMARY KEY, window_start BIGINT NOT NULL,
                attempts INTEGER NOT NULL)''')
            conn.execute('''CREATE TABLE IF NOT EXISTS auth_remember_sessions (
                token_hash TEXT PRIMARY KEY, email TEXT NOT NULL,
                password_fingerprint TEXT NOT NULL, expires_at BIGINT NOT NULL)''')
            yield conn
            conn.commit()
        except (sqlite3.Error, psycopg.Error, OSError, ValueError):
            if conn is not None:
                with suppress(sqlite3.Error, psycopg.Error):
                    conn.rollback()
            raise AuthError(_UNAVAILABLE) from None
        except BaseException:
            if conn is not None:
                with suppress(sqlite3.Error, psycopg.Error):
                    conn.rollback()
            raise
        finally:
            if conn is not None:
                with suppress(sqlite3.Error, psycopg.Error):
                    conn.close()

    def _take_attempt(self, email):
        identity = sha256(email.encode('utf-8')).hexdigest()
        now = int(time.time())
        with self._connection() as conn:
            # Expired entries are bounded by recent activity rather than growing forever.
            self._execute(conn, 'DELETE FROM auth_attempts WHERE window_start <= ?',
                          (now - ATTEMPT_WINDOW,))
            count = self._execute(conn, '''INSERT INTO auth_attempts
                (identity, window_start, attempts) VALUES (?, ?, 1)
                ON CONFLICT(identity) DO UPDATE SET attempts = auth_attempts.attempts + 1
                RETURNING attempts''', (identity, now)).fetchone()[0]
        # Commit even a rejected attempt: this limit survives reconnects and reruns.
        if count > MAX_ATTEMPTS:
            raise AuthError('Too many attempts. Please wait 5 minutes and try again.')

    def _clear_attempts(self, conn, email):
        self._execute(conn, 'DELETE FROM auth_attempts WHERE identity = ?',
                      (sha256(email.encode('utf-8')).hexdigest(),))

    def sign_up(self, email, password, confirmation):
        email = normalize_email(email)
        _validate_password(password)
        if password != confirmation:
            raise AuthError('Passwords do not match.')
        self._take_attempt(email)
        hashed = _HASHER.hash(password)
        with self._connection() as conn:
            inserted = self._execute(conn, '''INSERT INTO auth_users
                (email, password_hash, created_at) VALUES (?, ?, ?)
                ON CONFLICT(email) DO NOTHING RETURNING email''',
                (email, hashed, int(time.time()))).fetchone()
            if inserted is None:
                raise AuthError('An account with this email already exists. Please log in.')
            self._clear_attempts(conn, email)
        return email  # only after commit

    def login(self, email, password):
        email = normalize_email(email)
        if not isinstance(password, str) or not 1 <= len(password) <= MAX_PASSWORD_LENGTH:
            raise AuthError(_BAD_CREDENTIALS)
        self._take_attempt(email)
        with self._connection() as conn:
            user = self._execute(conn, 'SELECT password_hash FROM auth_users WHERE email = ?',
                                 (email,)).fetchone()
        hashed = user[0] if user else _dummy_hash()
        try:
            _HASHER.verify(hashed, password)
        except (VerificationError, InvalidHashError):
            raise AuthError(_BAD_CREDENTIALS) from None
        if user is None:
            raise AuthError(_BAD_CREDENTIALS)
        with self._connection() as conn:
            if _HASHER.check_needs_rehash(hashed):
                self._execute(conn, 'UPDATE auth_users SET password_hash = ? WHERE email = ? AND password_hash = ?',
                              (_HASHER.hash(password), email, hashed))
            self._clear_attempts(conn, email)
        return email

    def create_remember_session(self, verified_email):
        """Called only after password verification; store a digest, never the token."""
        token = secrets.token_hex(32)
        now = int(time.time())
        with self._connection() as conn:
            self._execute(conn, 'DELETE FROM auth_remember_sessions WHERE expires_at <= ?', (now,))
            user = self._execute(conn, 'SELECT password_hash FROM auth_users WHERE email = ?',
                                 (verified_email,)).fetchone()
            if user is None:
                raise AuthError(_BAD_CREDENTIALS)
            self._execute(conn, '''INSERT INTO auth_remember_sessions
                (token_hash, email, password_fingerprint, expires_at) VALUES (?, ?, ?, ?)''',
                (sha256(token.encode()).hexdigest(), verified_email,
                 sha256(user[0].encode()).hexdigest(), now + REMEMBER_SECONDS))
        return token

    def restore_remember_session(self, token):
        if not _valid_remember_token(token):
            return None
        with self._connection() as conn:
            row = self._execute(conn, '''SELECT s.email, s.password_fingerprint, u.password_hash
                FROM auth_remember_sessions s JOIN auth_users u ON u.email = s.email
                WHERE s.token_hash = ? AND s.expires_at > ?''',
                (sha256(token.encode()).hexdigest(), int(time.time()))).fetchone()
            if row and secrets.compare_digest(row[1], sha256(row[2].encode()).hexdigest()):
                return row[0]
        return None

    def revoke_remember_session(self, token):
        if _valid_remember_token(token):
            with self._connection() as conn:
                self._execute(conn, 'DELETE FROM auth_remember_sessions WHERE token_hash = ?',
                              (sha256(token.encode()).hexdigest(),))


def _valid_remember_token(token):
    return isinstance(token, str) and len(token) == 64 and all(c in '0123456789abcdef' for c in token)
