[server]
headless = true

[browser]
gatherUsageStats = false
[theme]
base = "dark"
primaryColor = "#6485ff"
backgroundColor = "#080e1b"
secondaryBackgroundColor = "#121c2e"
textColor = "#edf2ff"
font = "sans serif"
