[server]
headless = true

[browser]
gatherUsageStats = false
[theme]
base = "light"
primaryColor = "#087b89"
backgroundColor = "#f3f9f8"
secondaryBackgroundColor = "#edf5f4"
textColor = "#173b3a"
font = "sans serif"
